name: Update public content
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - 'i18n/**'
  workflow_dispatch:

jobs:
  update-public-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

      - name: Update public repository
        env:
          PROD_REPO_TOKEN: ${{ secrets.GH_PAT}}
        run: |
          git clone --depth 1 --branch main https://${{ secrets.GH_PAT}}@github.com/Consensys/docs-mm-helpcenter.git public-repo
          rm -rf public-repo/*
          cp -r docs i18n public-repo/
          cd public-repo
          git add .
          git commit -m "Update content from site backend"
          git push